import { IDataTable } from "../../ts/interfaces/main";

export const tableData: IDataTable[] = [
  {
    id: 1,
    company: "company",
    name: "name",
    additional: "additional",
    street: "street",
    postalCode: "postalCode",
    country: "country",
    iban: "iban",
    bic: "bic",
    bankName: "bankName",
    fax: "fax",
    email: "email",
    birthday: "birthday",
    homepage: "homepage",
  },
  {
    id: 2,
    company: "company",
    name: "name",
    additional: "additional",
    street: "street",
    postalCode: "postalCode",
    country: "country",
    iban: "iban",
    bic: "bic",
    bankName: "bankName",
    fax: "fax",
    email: "email",
    birthday: "birthday",
    homepage: "homepage",
  },
];

export const headTableData: string[] = [
  "",
  "company",
  "name",
  "additional",
  "street",
  "postalCode",
  "country",
  "iban",
  "bic",
  "bankName",
  "fax",
  "email",
  "birthday",
];
